name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew assembleDebug --stacktrace
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Lint
        run: ./gradlew :app:lintDebug
      - name: Detekt
        run: ./gradlew :app:detekt
      - name: ktlint
        run: ./gradlew :app:ktlintCheck


